window.Books = [
  {
    "title": "Vincent - Quadrinhos (Em Português do Brasil)",
    "image": "gv0923fd87c6009d694e28f9d2fff2d8dd",
    "creators": "Barbara Stok",
    "first_name": "Barbara",
    "last_name": "Stok",
    "ean_isbn13": 9788525431158,
    "upc_isbn10": "852543115X",
    "description": "Vencedora do Prêmio Holandês de Melhor Autor de HQ 2009 \"Stok retrata de forma brilhante e cheia de compaixão o artista ora num surto de loucura, ora sentado em meio aos trigais e girassóis de Arles, com a paisagem a um só tempo suave e alheia, e o homem impulsionado por uma paixão desesperada e radical.\" The Guardian \"Stok captura a alma de Vincent.\" Zone 5300 \"Como bônus, Stok incorpora cartas de Vincent a Theo. Ela faz o mesmo com suas pinturas, que vemos o artista criar e que Stok às vezes reproduz em páginas duplas. As imagens e a história se fortalecem mutuamente de uma maneira que seria impossível em qualquer outro meio de expressão.\" NRC Handelsblad Vincent van Gogh (1853-1890) e sua mente torturada conceberam uma arte fascinante que transcendeu sua própria história para se tornar um dos mais expressivos e maravilhosos conjuntos de pinturas jamais concebidos. Nesta graphic novel de traços pop originalíssimos, Barbara Stok retrata de forma delicada e luminosa os últimos anos da vida do pintor holandês, passados na França, onde encontrou não apenas seu fim, mas também a natureza e a luz que imortalizou em seus quadros. Em 1888, após uma estadia de dois anos em Paris, Vincent van Gogh muda-se para Arles, no sul da França. A luminosidade, os espaços abertos e as paisagens bucólicas da região, além do próprio contato com a natureza, fornecem ao artista a matéria-prima para aquela que é considerada a fase mais rica e revolucionária de sua arte. Se por um lado o ambiente o enche de contentamento e esperança, por outro agravam-se seu desequilíbrio e sua angústia, piorados ainda pela falta de dinheiro e de perspectivas concretas de futuro e pela culpa de ser um fardo para o irmão, Theo, que o sustentava financeiramente. É esse turbulento e rico período, não apenas crucial para a compreensão do gênio Van Gogh como também emblemático de sua existência, que a artista gráfica Barbara Stok retrata, com um colorido e uma sing[...]",
    "publisher": "L&PM",
    "publish_date": "",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Structure and Dynamics of Organizations and Groups",
    "image": "akecb1f4a4ee989b642f665bd3ef5c01fa",
    "creators": "Eric Berne",
    "first_name": "Eric",
    "last_name": "Berne",
    "ean_isbn13": 9780394170480,
    "upc_isbn10": 394170482,
    "description": "",
    "publisher": "",
    "publish_date": "",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Como Saber Se Seu Gato Está Planejando Matar Você (Em Português do Brasil)",
    "creators": "Vários Autores",
    "first_name": "Vários",
    "last_name": "Autores",
    "ean_isbn13": 9788542803372,
    "upc_isbn10": "854280337X",
    "description": "Aquele ser felpudo que gosta de afiar as unhas no seu sofá pode até parecer um gatinho inofensivo. Na cabeça dele, porém, é um felino altamente perigoso. É uma pantera, um tigre, um enorme leão-da-montanha! Seu gato gosta de pular na sua cama de manhã, acordando você bem cedinho para fazer massagem na sua barriga? Se você considera isso uma demonstração de carinho do seu bichano, cuidado! Talvez ele esteja verificando seus órgãos internos, procurando por pontos fracos para usar quando... for matar você! Fenômeno na internet, Como saber se seu gato está planejando matar você é brilhante e extremamente engraçado. Seja você um gatófilo inveterado ou simples simpatizante, encontrará aqui uma maneira divertida de compreender a mente desse felino tão misterioso. Você pode até morrer, mas de rir!",
    "publisher": "Novo Século",
    "publish_date": "2014-01-01",
    "notes": "",
    "price": "R$ 8,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "As Cronicas de Narnia - Volume Unico (Em Portugues do Brasil)",
    "image": "0591bc3cb9fce066c5b917b851fb986894",
    "creators": "Clive Staples Lewis",
    "first_name": "Clive",
    "last_name": "Lewis",
    "ean_isbn13": 9788578270698,
    "upc_isbn10": "857827069X",
    "description": "Viagens ao fim do mundo, criaturas fantásticas e batalhas épicas entre o bem e o mal. Este livro apresenta as sete crônicas de Nárnia integralmente, num único volume. Os livros são apresentados de acordo com a ordem de preferência do autor, cada capítulo com uma ilustração do artista Pauline Baynes. 'As crônicas de Nárnia' apresenta aventuras, personagens e fatos que falam aos leitores de todas as idades.",
    "publisher": "Wmf Martins Fontes",
    "publish_date": "2009-01-01",
    "notes": "",
    "price": "R$ 15,00",
    "length": 751,
    "copies": 1
  },
  {
    "title": "Bro Code (Em Inglês)",
    "creators": "Kuhn Matt Stinson Barney",
    "first_name": "Kuhn",
    "last_name": "Barney",
    "ean_isbn13": 9781847399304,
    "upc_isbn10": 1847399304,
    "description": "Like brand new, hardly used",
    "publisher": "Simon & Schuster",
    "publish_date": "2009-10-01",
    "notes": "",
    "price": "R$ 15,00",
    "length": 192,
    "copies": 1
  },
  {
    "title": "Playbook: O Manual da Conquista (Em Portugues do Brasil)",
    "image": "nh5eeaec9e209c01c0b6ae6d7cf4f5c91f",
    "creators": "Barney Stinson",
    "first_name": "Barney",
    "last_name": "Stinson",
    "ean_isbn13": 9788580576627,
    "upc_isbn10": 8580576628,
    "description": "Desde o inicio dos tempos, o homem tem procurado respostas para o questionamento mais fundamental de todos: Por que estou aqui... em vez de estar com uma garota? A procura acabou. Agora, com a ajuda de Playbook: O manual da conquista , o leitor sera capaz de abordar a garota que quiser, descobrir o que ela mais deseja e faze-la se apaixonar por ele.Com mais de setenta tecnicas de seducao desenvolvidas pelo guru da conquista e exemplo de perfeicao Barney Stinson , qualquer homem podera se tornar um perfeito conquistador.Repleto de dicas, macetes, truques e muita conversa fiada, o popular personagem da serie de teve How I Met Your Mother sugere dezenas de maneiras de abordar uma mulher e ser bem-sucedido. Com as dicas dele nenhum homem ficara sozinho.",
    "publisher": "INTRINSECA - SEXTANTE",
    "publish_date": "2015-01-01",
    "notes": "",
    "price": "R$ 8,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Código BRO",
    "creators": "Barney Stinson",
    "first_name": "Barney",
    "last_name": "Stinson",
    "ean_isbn13": 9788580574593,
    "upc_isbn10": 8580574595,
    "description": "Todos vivemos sob um código de conduta pessoal. Alguns o chamam de moralidade. Outros, de religião. Os Bros chamam de Código Bro. O que é um Bro? Um Bro é um companheiro em quem você poda confiar eternamente e que estará sempre pronto para ajudá-lo - a menos que tenha coisa melhor para fazer. Agora imagine um livro que ensine os Bros a viver em harmonia, ter casos de uma noite só, levar sempre a quantidade certa de bebida para uma festa ou fingir um profundo conhecimento de esportes e mecânica, entre outras habilidades incríveis. Barney Stinson, um homem lindo e disponível, reconhecido por ter revolucionado a blogosfera com seu www.barneysblog.com, compilou esse código para que Bros do mundo inteiro possam esquecer suas diferenças e estreitar os laços de irmandade. Então, e somente então, conseguirão trabalhar juntos para vencer o maior desafio enfrentado pelo homem: transar. O livro é parte integrante da série de TV How I Met Your Mother, que está na 9ª temporada e tem mais de 500 mil seguidores no Twitter e 24 milhões de curtidas no Facebook. No Brasil, o seriado é transmitido pelo canal pago Fox, pelo serviço de televisão via internet Netflix, e estreará na TV aberta, na Band, em 7 de janeiro, intitulado Como Conheci Sua Mãe. O personagem Barney Stinson tem mais de 600 mil seguidores no Twitter e 4 milhões no Facebook. A série ganhou 18 prêmios, entre eles o People's Choice Award de Melhor Ator de Comédia para Neil Patrick Harris, intérprete de Barney Stinson. Conhecida por ser multiplataforma, a série dá continuidade ao livro em sites como www.barneysblog.com e com os clipes de Robin Sparkles, personagem da atriz Colbie Smulders, que têm mais de 3 milhões de visualizações no YouTube.",
    "publisher": "INTRINSECA - SEXTANTE",
    "publish_date": "2014-01-01",
    "notes": "",
    "price": "R$ 8,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Book of Bunny Suicides",
    "image": "m302dd88e8950a09fa433d4a63cf00ee9d",
    "creators": "Andy Riley",
    "first_name": "Andy",
    "last_name": "Riley",
    "ean_isbn13": 9780452285187,
    "upc_isbn10": 452285186,
    "description": "Rabbits.&nbsp; We&#039;ll never quite know why, but sometimes they decide they&#039;ve just had enough of this world- and that&#039;s when they start getting inventive.&nbsp; The Book of Bunny Suicides follows over one hundred bunnies as they find ever more outlandish ways to do themselves in.&nbsp; From an encounter with the business end of Darth Vader&#039;s lightsaber, to supergluing themselves to a diving submarine, to hanging around underneath a loose stalactite, these bunnies are serious about suicide. Illustrated in a stark and simple style, The Book of Bunny Suicides is a collection of hilarious and outrageous cartoons that will appeal to anyone in touch with their evil side.",
    "publisher": "Plume",
    "publish_date": "2003-12-30",
    "notes": "",
    "price": "R$ 20,00",
    "length": 80,
    "copies": 1
  },
  {
    "title": "San Francisco - Insight City Guide",
    "creators": "Insight Guides Staff",
    "first_name": "Insight",
    "last_name": "Staff",
    "ean_isbn13": 9781786715401,
    "upc_isbn10": 1786715406,
    "description": "A fully-overhauled edition by our expert San Francisco author. Stunning photography brings this wonderful city and its people to life. Highlights of the city's top attractions are covered in our Best of San Francisco section, broken down into categories like the best walks, the best bars and the best child-friendly activities in the city. Descriptive accounts of each neighbourhood cover the whole city from Fisherman's Wharf to SoMA. The Day Trips from San Francisco chapter includes Big Sur, Napa and Mendocino. Detailed, high-quality maps throughout will help you get around and travel tips give you all the essential information for planning a memorable trip. About Insight Guides: Insight Guides has over 40 years' experience of publishing high-quality, visual travel guides. We produce around 400 full-colour print guide books and maps as well as picture-packed eBooks to meet different travellers' needs. Insight Guides' unique combination of beautiful travel photography and focus on history and culture together create a unique visual reference and planning tool to inspire your next adventure. 'Insight Guides has spawned many imitators but is still the best of its type.' - Wanderlust Magazine",
    "publisher": "APA Publications Services",
    "publish_date": "2017-04-01",
    "notes": "",
    "price": "R$ 30,00",
    "length": 288,
    "copies": 1
  },
  {
    "title": "1000 Lugares Para Conhecer Antes de Morrer (Em Portugues do Brasil)",
    "image": "oqe73bfe39e79b9076e1f8311f1a967825",
    "creators": "Patricia Schultz",
    "first_name": "Patricia",
    "last_name": "Schultz",
    "ean_isbn13": 9788575422168,
    "upc_isbn10": 8575422162,
    "description": "Seja voce e um viajante inveterado ou alguem que simplesmente adora ler sobre lugares e culturas diferentes, vai se deliciar com esta extraordinaria selecao do que existe de melhor para ser visto e apreciado nos cinco continentes - de belezas naturais a maravilhas criadas pelo homem. Entre as opcoes selecionadas pelo olhar perspicaz de Patricia Shultz para atender a todos os gostos e bolsos estao reservas ecologicas, ruinas sagradas, resorts, restaurantes, vilarejos esquecidos pelo tempo, museus, teatros, catedrais, fiordes, cavernas, cruzeiros, safaris, trilhas, passeios de balao e ilhas fantasticas. Sem falar nos eventos culturais, artisticos, gastronomicos, religiosos e esportivos e nos incriveis roteiros por palacios e vinhedos. Ao final de cada texto, este guia lhe diz como chegar la, fornece telefones, sites, e-mails, indica a melhor epoca para o passeio e lista precos aproximados no Brasil e no exterior.",
    "publisher": "Sextante",
    "publish_date": "2006-01-01",
    "notes": "",
    "price": "R$ 8,00",
    "length": 752,
    "copies": 1
  },
  {
    "title": "E Se? (Em Portugues do Brasil)",
    "image": "8jeddf75e9411049975a36205657537ad1",
    "creators": "Randall Munroe",
    "first_name": "Randall",
    "last_name": "Munroe",
    "ean_isbn13": 9788535924831,
    "upc_isbn10": 8535924833,
    "description": "Garoto prodigio da NASA, Randall Munroe tornou-se conhecido com a iconica serie em quadrinhos XKCD, que passou a publicar na internet em 2005. Desde entao, milhoes de pessoas visitam semanalmente o xkcd.com em busca de suas figuras desenhadas com palitinhos e seus comentarios sobre ciencia, tecnologia e amor. Munroe nao tem exatamente leitores, e sim um sequito de seguidores apaixonados.Mas os fas do XKCD costumam fazer perguntas estranhas a Munroe. O que aconteceria se voce rebatesse uma bola de beisebol a 90% da velocidade da luz? Qual a velocidade maxima permitida para passar de carro por uma lombada sem morrer? Se os robos causassem o apocalipse, quanto tempo a humanidade duraria? Em busca de atender a curiosidade de seus leitores, Munroe criou o tambem imensamente popular E SE?, um blog destinado a resolver essas e outras grandes questoes da humanidade. Para encontrar as respostas, Munroe cria complexas simulacoes computadorizadas, le dezenas de memorandos do exercito, resolve equacoes diferenciais e consulta operadores de usinas nucleares. Suas respostas sao uma obra-prima da clareza e do humor. Em geral elas terminam com a aniquilacao da humanidade, ou pelo menos numa grande explosao.Nas listas dos mais vendidos mesmo antes de ser publicado, E se? traz questoes nunca antes respondidas, alem de versoes expandidas e atualizadas das perguntas mais populares do blog. Leitura obrigatoria nao so para os fas do XKCD, mas para todos que ja se viram considerando hipoteses absurdas e descabidas. Randall Munroe esta ao seu lado.",
    "publisher": "Companhia das Letras2",
    "publish_date": "2014-01-01",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Hellsing - Vol.1",
    "image": "cz13bdc4e2d16e7c7046fc2193dcdea44a",
    "creators": "Kohta Hirano",
    "first_name": "Kohta",
    "last_name": "Hirano",
    "ean_isbn13": 9788545700319,
    "upc_isbn10": 8545700318,
    "description": "A Ordem Real dos Cavaleiros Protestantes Para resolver o caso de um estranho pastor de hábitos macabros, é chamada a Organização Hellsing, responsável por livrar a Inglaterra dos males que espreitam na noite. Alucard é a principal arma da Hellsing contra estes seres, e sua história se cruza com a da novata Seras Victoria e a da chefe da organização, Integra Wingates Hellsing.[...]",
    "publisher": "JBC",
    "publish_date": "2015-01-01",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Dexter (Em Portugues do Brasil)",
    "creators": "Jeff Lindsay",
    "first_name": "Jeff",
    "last_name": "Lindsay",
    "ean_isbn13": 9788542203356,
    "upc_isbn10": 8542203356,
    "description": "Dexter, o psicopata dos psicopatas, depois de fazer grande sucesso nos livros e na TV, agora invade as paginas dos quadrinhos.Nessa historia completa, o devotado personagem deve lidar com um fantasma de seu passado: Steve Gonzalez, um valentao que perseguiu Dexter na epoca da escola.Porem, ele hoje e um lantropo, considerado a Madre Teresa de Miami por causa de sua Fundacao Esperanca, que reabilita viciados. Apos um inocente reencontro em uma festa, Dexter acredita que nunca mais o vera. No entanto, uma serie de assassinatos coloca os dois em rota de colisao.",
    "publisher": "Planeta do Brasil",
    "publish_date": "2014-01-01",
    "notes": "Capa Dura",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Ghost in the Shell 2.0 (Em Portugues do Brasil)",
    "creators": "Shirow Masamune",
    "first_name": "Shirow",
    "last_name": "Masamune",
    "ean_isbn13": 9788545703716,
    "upc_isbn10": 8545703716,
    "description": "The Ghost in the Shell 2.0 - Manmachine Interface é a continuação do clássico mangá de Masamune Shirow. The Ghost in the Shell é uma obra à frente de seu próprio tempo. Bebendo de fontes como Blade Runner - O Caçador de Androides, Masamune Shirow criou um universo com identidade própria e que influenciou - e ainda influencia - a cultura pop mundial. Para The Ghost in the Shell 2.0, Shirow atualizou sua fórmula e seus personagens. A ação se passa no mundo virtual. É nesse ambiente onde quase tudo é possível e repleto de recursos cibernéticos que lhe permitem até controlar multiplas personalidades suas que a \"nova\" Mokoto precisa rastrear e localizar uma nova inteligência artificial e, ao mesmo tempo, impedir que ela caia nas mãos erradas. Os questionamentos existencialistas tão marcantes do primeiro The Ghost in the Shell também aparecem em Manmachine Interface, porém dividem o espaço com uma narrativa mais dinâmica, repleta de ação e referências à obra original.",
    "publisher": "",
    "publish_date": "",
    "notes": "",
    "price": "R$ 35,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Ghost in the Shell (Em Português do Brasil)",
    "creators": "Shirow Masamune",
    "first_name": "Shirow",
    "last_name": "Masamune",
    "ean_isbn13": 9788545702320,
    "upc_isbn10": 8545702329,
    "description": "Influenciado por obras \"cyberpunk\" do final dos anos 1980 como Akira e por filmes como Blade Runner - O Caçador de Androides, o cenário escolhido por Masamune Shirow para The Ghost in the Shell foi o futuro distópico de 2029, onde a alta tecnologia se mistura a uma sociedade decadente e desigual.É nesse mundo à beira do colapso que a Major Motoko Kusanagi encabeça a Seção 9 da Segurança Pública japonesa. Motoko é uma ciborgue altamente treinada incumbida de desmantelar uma série de crimes cibernéticos realizados por um hacker conhecido como o Mestre dos Fantoches. Em meio à caça ao criminoso virtual, Masamune Shirow insere na trama questionamentos existencialistas, ponderando até mesmo se alguém provido meramente de Inteligência Artificial é, de fato, um ser vivo. E foi exatamente essa mistura de ficção científica, ação e temas filosóficos que fizeram do mangá The Ghost in the Shell uma leitura obrigatória.",
    "publisher": "JBC",
    "publish_date": "2016-01-01",
    "notes": "",
    "price": "R$ 35,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Universo De Sandman: A Casa Dos Sussurros Vol. 1",
    "image": "b52598972fef984f7b583ecd56984a840ccfc760",
    "creators": "",
    "first_name": "",
    "last_name": "",
    "ean_isbn13": 9788542621389,
    "upc_isbn10": 8542621387,
    "description": "",
    "publisher": "Panini",
    "publish_date": "",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 2
  },
  {
    "title": "O Universo de Sandman. Os Livros da Magia Volume 1",
    "image": "j7c678a9bb260ff4384e784760b9f4d8fa",
    "creators": "_",
    "first_name": "_",
    "last_name": "_",
    "ean_isbn13": 9788542621471,
    "upc_isbn10": 8542621476,
    "description": "",
    "publisher": "Panini",
    "publish_date": "",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 2
  },
  {
    "title": "The Wicked + The Divine",
    "image": "0k2a60270b16c05c55c9867be17700fc52",
    "creators": "Vários Autores",
    "first_name": "Vários",
    "last_name": "Autores",
    "ean_isbn13": 9788542811193,
    "upc_isbn10": 8542811194,
    "description": "O TERCEIRO VOLUME DA SÉRIE INDICADA AO EISNER E BEST-SELLER DO THE NEW YORK TIMES Ser imortal não significa viver para sempre... A cada 90 anos, aproximadamente, doze deuses reencarnam no corpo de jovens adultos. Eles são carismáticos, perspicazes e atraem grandes multidões. São capazes de levar qualquer um ao êxtase. Há rumores de que podem realizar milagres. Eles salvam vidas, seja metafórica ou concretamente. Eles são amados. Eles são odiados. Eles são incríveis. E em menos de dois anos estarão todos mortos. Isso já aconteceu uma vez. E vai acontecer de novo... Assim se constrói “The Wicked + The Divine”, uma fascinante alegoria para os jovens de hoje sobre a glória efêmera erigida como valor supremo na sociedade moderna. Fenômeno de público e crítica, a série concebida por Kieron Gillen e Jamie McKelvie (criadores de “Phonogram” e “Jovens Vingadores”) obteve diversas indicações ao Prêmio Eisner, e agora chega ao terceiro volume, “Suicídio Comercial”, que reúne as edições 12 a 17 da aclamada HQ, além de vários extras. “Esta HQ é tão boa que eu quase fico brava com ela.” – ZOE QUINN, Depression Quest, Crash Override. “A HQ perfeita sobre amar demais uma coisa.” – EVAN NARCISSE, Kotaku. “Lindo, fantástico...” – EMILY MACKAY, The Guardian. “Devastador...” – LAURA HUDSON, Wired.",
    "publisher": "",
    "publish_date": "",
    "notes": "Capa Dura",
    "price": "R$ 20,00",
    "length": 192,
    "copies": 1
  },
  {
    "title": "The wicked + The divine: Fandêmonio",
    "creators": "Kieron Gillen",
    "first_name": "Kieron",
    "last_name": "Gillen",
    "ean_isbn13": 9788542811186,
    "upc_isbn10": 8542811186,
    "description": "Imortal não significa viver para sempre... A cada 90 anos, aproximadamente, doze deuses reencarnam no corpo de jovens adultos. Eles são carismáticos, perspicazes e atraem grandes multidões. São capazes de levar qualquer um ao êxtase. Há rumores de que podem realizar milagres. Eles salvam vidas, seja metafórica ou concretamente. Eles são amados. Eles são odiados. Eles são incríveis. E em menos de dois anos estarão todos mortos. Isso já aconteceu uma vez. E vai acontecer de novo...",
    "publisher": "Geektopia",
    "publish_date": "2017-01-01",
    "notes": "Capa Dura",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Wicked + The Divine(Em Portugues do Brasil)",
    "creators": "Kieron Gillen",
    "first_name": "Kieron",
    "last_name": "Gillen",
    "ean_isbn13": 9788542809992,
    "upc_isbn10": 8542809998,
    "description": "Século XXI. Deuses caminham entre nós e se assemelham a ícones pop do nosso tempo. Assim se constrói The Wicked + The Divine, uma fascinante alegoria para os jovens de hoje sobre a glória efêmera erigida como valor supremo na sociedade moderna. Fenômeno de público e crítica, a série criada por Kieron Gillen e Jamie McKelvie (criadores de Phonogram e Jovens Vingadores ) obteve diversas indicações ao Prêmio Eisner, e agora chega ao leitor brasileiro com exclusividade pelo selo Geektopia.",
    "publisher": "",
    "publish_date": "",
    "notes": "Capa Dura",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Akira - volume 3 (Em Portugues do Brasil)",
    "image": "5699354610bfffec7184e40db7a27aaa87",
    "creators": "Katsuhiro Otomo",
    "first_name": "Katsuhiro",
    "last_name": "Otomo",
    "ean_isbn13": 9788545707226,
    "upc_isbn10": 8545707223,
    "description": "Kaneda e Kei conseguem escapar da base secreta subterrânea, levando com eles um misterioso garoto com o número 28 na palma da mão. Mal sabiam eles que esse indivíduo era AKIRA, o maior segredo da nação, que tinha despertado. A disputa pela posse do garoto agora ocorre em três frentes: de um lado, a guerrilha comandada por Nezu; do outro, o Exército sob as ordens do Coronel; e por último, a seita da sacerdotiza Miyako. Quem o tiver em mãos obterá um grande poder ou? o aguardado terceiro volume de AKIRA já está disponível.",
    "publisher": "",
    "publish_date": "",
    "notes": "",
    "price": "R$ 40,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Akira 2",
    "creators": "Katsuhiro Otomo",
    "first_name": "Katsuhiro",
    "last_name": "Otomo",
    "ean_isbn13": 9788545703679,
    "upc_isbn10": 8545703678,
    "description": "Tetsuo renasce como Número 41, com um poder maior do que Kaneda ou o governo poderiam imaginar. Depois de ingerir a cápsula roubada, escapa do controle do Coronel e ataca a fortaleza escondida embaixo do Estádio Olímpico. Enquanto isso, Miyako, fundadora de uma nova religião, prevê uma grande catástrofe, provocada pelo despertar de AKIRA. O que é AKIRA, o maior segredo da nação? o aguardado segundo volume do épico de ficção científica AKIRA já está disponível.",
    "publisher": "JBC",
    "publish_date": "2018-01-01",
    "notes": "",
    "price": "R$ 40,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Akira - Volume 1 (Em Português do Brasil)",
    "image": "jh1ba4f3ce3e1456ba678180d590059a59",
    "creators": "Katsuhiro Otomo",
    "first_name": "Katsuhiro",
    "last_name": "Otomo",
    "ean_isbn13": 9788545702870,
    "upc_isbn10": 8545702876,
    "description": "Um dos maiores mangás de todos os tempos volta ao Brasil em uma edição especial totalmente remasterizada e em seu formato e leitura originais. Neste primeiro volume, em um mundo pós-apocaliptico, conhecemos Kaneda e Tetsuo, dois amigos membros de uma gangue de motoqueiros arruaceiros que terão suas vidas drasticamente mudadas após o atropelamento de uma estranha criança. Depois do acidente Tetsuo passa a despertar estranhos poderes que acabam chamando a atenção do Governo o qual, atualmente, trabalha em experiências secretas com paranormais.",
    "publisher": "JBC",
    "publish_date": "2017-01-01",
    "notes": "",
    "price": "R$ 40,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Fundação (Em Português do Brasil)",
    "image": "1167468711f715e18ef68286bae5cf58cfb51a51e",
    "creators": "Isaac Asimov",
    "first_name": "Isaac",
    "last_name": "Asimov",
    "ean_isbn13": 9788576570660,
    "upc_isbn10": 8576570661,
    "description": "A humanidade vive o seu momento mais próspero. Há mais de dez mil anos um império reina absoluto sobre todos os mundos habitados. Ninguém acredita que esse tempo luminoso possa ter fim. Ninguém, exceto Hari Seldon, o criador de uma ciência revolucionária capaz de prever o futuro da raça humana. Seldon antevê a chegada de uma era de trevas jamais vista e inevitável. Apenas ele pode minimizar os estragos; garantir que o homem se reerga o mais rápido possível. Para isso, tem um plano, que deverá ser executado através dos séculos pelos membros da Fundação.",
    "publisher": "Aleph",
    "publish_date": "2009-01-01",
    "notes": "",
    "price": "R$ 10,00",
    "length": 240,
    "copies": 1
  },
  {
    "title": "Os Robôs da Alvorada (Em Português do Brasil)",
    "image": "0s389ad83145feb21e7f4f23da16254d1a",
    "creators": "Isaac Asimov",
    "first_name": "Isaac",
    "last_name": "Asimov",
    "ean_isbn13": 9788576572657,
    "upc_isbn10": 8576572656,
    "description": "Dois anos apos desvendar um assassinato em Solaria, o detetive Elijah Baley e novamente convocado para uma investigacao em um Mundo Exterior. Com ajuda de seu parceiro e amigo R. Daneel Olivaw, Baley tera de solucionar um crime bastante peculiar: um caso de roboticidio que coloca em xeque a reputacao de um importante estudioso naquele planeta. No terceiro volume da consagrada Serie dos Robos, em meio a mais evoluida colonia humana fora da Terra, Baley esta prestes a enfrentar conflitos ainda mais complexos, que envolvem a seguranca de Elijah Baley, interesses interplanetarios e o destino da propria humanidade.",
    "publisher": "Aleph",
    "publish_date": "2015-01-01",
    "notes": "",
    "price": "R$ 30,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Segunda Fundação - Volume 3 (Em Português do Brasil)",
    "image": "cf926d1f0e315af4e52fac25a29b60718b",
    "creators": "Isaac Asimov",
    "first_name": "Isaac",
    "last_name": "Asimov",
    "ean_isbn13": 9788576570684,
    "upc_isbn10": 8576570688,
    "description": "Hari Seldon previu que a humanidade perderia seu dom&iacute;nio sobre a gal&aacute;xia. Para evitar esse desastre, elaborou um plano que, seguido &agrave; risca, em mil anos deveria fazer surgir uma nova era de gl&oacute;rias para o homem. Mas ele n&atilde;o contava com o Mulo, um ser mutante que colocar todo o plano a perder. Seu objetivo &eacute; derrotar a Funda&ccedil;&atilde;o para que um novo Imp&eacute;rio se erga em torno de seus fant&aacute;sticos poderes mentais. Mas, para consolidar sua vit&oacute;ria, ainda ter&aacute; de enfrentar um inimigo igualmente poderoso, conhecido como a Segunda Funda&ccedil;&atilde;o. &#039;Segunda funda&ccedil;&atilde;o&#039; &eacute; o terceiro livro da trilogia da Funda&ccedil;&atilde;o, composta ainda pelos livros &#039;Funda&ccedil;&atilde;o&#039; (livro 1) e &#039;Funda&ccedil;&atilde;o e imp&eacute;rio&#039; (livro 2).[...]",
    "publisher": "Aleph",
    "publish_date": "",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Fundação e Império (Em Português do Brasil)",
    "creators": "Isaac Asimov",
    "first_name": "Isaac",
    "last_name": "Asimov",
    "ean_isbn13": 9788576570677,
    "upc_isbn10": "857657067X",
    "description": "O Imp&eacute;rio Gal&aacute;tico est&aacute; &agrave; beira do colapso. Ainda assim, numa tentativa ousada, o General Bel Riose decide lan&ccedil;ar um ataque contra a Funda&ccedil;&atilde;o. Mas ser&aacute; que a ofensiva desesperada ir&aacute; impedir o destino profetizado h&aacute; s&eacute;culos por Hari Seldon? E quem seria, afinal, o Mulo? Este &eacute; o segundo livro da Trilogia da Funda&ccedil;&atilde;o, vencedora do pr&ecirc;mio Hugo como a melhor s&eacute;rie de FC de todos os tempos.[...]",
    "publisher": "Aleph",
    "publish_date": "",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Retalhos - Blankets (Em Portugues do Brasil)",
    "image": "jwe03ba66fb42a12ba43cb38aef80580bb",
    "creators": "Craig Thompson",
    "first_name": "Craig",
    "last_name": "Thompson",
    "ean_isbn13": 9788535914481,
    "upc_isbn10": 853591448,
    "description": "Uma das graphic novels mais premiadas dos ultimos tempos, Retalhos e um relato autobiografico da vida no Meio Oeste americano. Thompson retrata sua propria historia, da infancia ate o inicio da vida adulta, numa cidadezinha de Wisconsin, no centro dos Estados Unidos, que parece estar sempre coberta pela neve. Seu crescimento e marcado pelo temor a Deus transmitido por sua familia, seu colegio, seu pastor e as tragicas passagens biblicas que le , que se interpoe contra seus desejos, como o de se expressar pelo desenho.Ao mesmo tempo Thompson descreve a relacao com o irmao mais novo, com quem ele dividiu a cama durante toda a infancia. Conforme amadurecem, os irmaos se distanciam, episodio narrado com rara sensibilidade pelo autor.Com a adolescencia, seus desejos se expandem e acabam tomando forma em Raina uma garota vivaz, de alma poetica e impulsiva, quase o oposto total de Thompson com quem comeca a relacao que mudara a visao que ele tem da familia, de Deus, do futuro e, enfim, do proprio amor. Retalhos traz as dores e as paixoes dos melhores romances de formacao mas dentro de uma linguagem grafica propria e extremamente original.",
    "publisher": "Quadrinhos Na Cia",
    "publish_date": "2009-05-21",
    "notes": "",
    "price": "R$ 25,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Batman. Arkham Knight (Em Português do Brasil)",
    "image": "aq3e3715c8390f0e0e47ace799ab53b18f",
    "creators": "Marv Wolfman",
    "first_name": "Marv",
    "last_name": "Wolfman",
    "ean_isbn13": 9788566636826,
    "upc_isbn10": 8566636821,
    "description": "O morcego e a caveira finalmente juntos Era inevitável: o Cavaleiro das Trevas e a DarkSide Books acabam de unir forças. E já podemos avistar o bat- sinal do que vem por aí: uma das mais sombrias aventuras do eterno Homem-Morcego. Batman: Arkham Knight é a adaptação literária oficial do game que conquistou fãs e críticos em 2015. Uma parceria entre a DC Comics, a Warner e a DarkSide Books que virá com aquele padrão quase psicopata de qualidade que os fãs brasileiros merecem. Se você já jogou Arkham Knight, prepare-se para reviver a história com uma resolução muito maior que a de qualquer console ou PC: a da sua imaginação. As páginas do romance têm adrenalina de sobra, e mesmo quem não é íntimo dos videogames vai se sentir explorando os becos escuros de Gotham City. Tudo começa um ano após a morte do Coringa. A cidade, que havia se transformado num hospício a céu aberto, finalmente volta à sua rotina normal. Mas é claro que a paz não pode ser duradoura em uma metrópole que esconde vilões como Charada, Pinguim, Hera Venenosa, Arlequina e Duas Caras.",
    "publisher": "DarkSide",
    "publish_date": "2016-01-01",
    "notes": "Capa Dura",
    "price": "R$ 25,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Games People Play: The Basic Handbook of Transactional Analysis.",
    "image": "akecb1f4a4ee989b642f665bd3ef5c01fa",
    "creators": "Eric Berne",
    "first_name": "Eric",
    "last_name": "Berne",
    "ean_isbn13": 9780345410030,
    "upc_isbn10": 345410033,
    "description": "We think we&rsquo;re relating to other people&ndash;but actually we&rsquo;re all playing games.Forty years ago, Games People Play revolutionized our understanding of what really goes on during our most basic social interactions. More than five million copies later, Dr. Eric Berne&rsquo;s classic is as astonishing&ndash;and revealing&ndash;as it was on the day it was first published. This anniversary edition features a new introduction by Dr. James R. Allen, president of the International Transactional Analysis Association, and Kurt Vonnegut&rsquo;s brilliant Life magazine review from 1965.We play games all the time&ndash;sexual games, marital games, power games with our bosses, and competitive games with our friends. Detailing status contests like &ldquo;Martini&rdquo; (I know a better way), to lethal couples combat like &ldquo;If It Weren&rsquo;t For You&rdquo; and &ldquo;Uproar,&rdquo; to flirtation favorites like &ldquo;The Stocking Game&rdquo; and &ldquo;Let&rsquo;s You and Him Fight,&rdquo; Dr. Berne exposes the secret ploys and unconscious maneuvers that rule our intimate lives.Explosive when it first appeared, Games People Play is now widely recognized as the most original and influential popular psychology book of our time. It&rsquo;s as powerful and eye-opening as ever.",
    "publisher": "Ballantine Books",
    "publish_date": "1996-08-27",
    "notes": "",
    "price": "R$ 30,00",
    "length": 216,
    "copies": 1
  },
  {
    "title": "Unnatural Selection: Choosing Boys Over Girls, and the Consequences of a World Full of Men",
    "creators": "Mara Hvistendahl",
    "first_name": "Mara",
    "last_name": "Hvistendahl",
    "ean_isbn13": 9781586488505,
    "upc_isbn10": 1586488503,
    "description": "Finalist for the Pulitzer PrizeFinalist for the Los Angeles Times Book PrizeA Wall Street Journal Best Book of 2011A Slate Best Book of 2011A Discover Magazine Best Book of 2011Lianyungang, a booming port city, has China&#039;s most extreme gender ratio for children under four: 163 boys for every 100 girls. These numbers don&#039;t seem terribly grim, but in ten years, the skewed sex ratio will pose a colossal challenge. By the time those children reach adulthood, their generation will have twenty-four million more men than women.The prognosis for China&#039;s neighbors is no less bleak: Asia now has 163 million females &quot;missing&quot; from its population. Gender imbalance reaches far beyond Asia, affecting Georgia, Eastern Europe, and cities in the U.S. where there are significant immigrant populations. The world, therefore, is becoming increasingly male, and this mismatch is likely to create profound social upheaval.Historically, eras in which there have been an excess of men have produced periods of violent conflict and instability. Mara Hvistendahl has written a stunning, impeccably-researched book that does not flinch from examining not only the consequences of the misbegotten policies of sex selection but Western complicity with them.",
    "publisher": "PublicAffairs",
    "publish_date": "2011-06-07",
    "notes": "Capa Dura",
    "price": "R$ 70,00",
    "length": 336,
    "copies": 1
  },
  {
    "title": "Gerenciamento de Projetos Para Leigos",
    "image": "fa449955d22865ca4f681391112c4580a872b324",
    "creators": "Stanley E. Portny",
    "first_name": "Stanley",
    "last_name": "Portny",
    "ean_isbn13": 9788550809076,
    "upc_isbn10": 8550809071,
    "description": "O S P R I M E I R O S P A S S O S P A R A O S U C E S S O ! Seu guia mais vendido, totalmente reformulado! No mundo empresarial global de hoje, consciente dos custos e pressionado pelo tempo, prazos de projetos apertados e expectativas exigentes são a norma. Como equilibrar todas as habilidades e responsabilidades necessárias para brilhar como uma estrela no gerenciamento de projetos? Neste guia best-seller, um renomado especialista da área oferece tudo de que você precisa para gerenciar projetos com sucesso do início ao fim - sem nunca deixar a peteca cair. Contém no livro: - Siga as melhores práticas das 5a e 6a edições do Guia PMBOK - Motive qualquer equipe para a produtividade máxima - Execute projetos no prazo com extrema eficiência Abra este livro e descubra como... - Entender a gênese de um projeto - Manter projetos organizados - Formar equipes de alto desempenho - Lidar com riscos - Monitorar o progresso - Usar a última tecnologia - Finalizar seu projeto Acesse o site www.paraleigos.com.br e conheça outros títulos!",
    "publisher": "Editora Alta Books",
    "publish_date": "2019-09-28",
    "notes": "",
    "price": "R$ 30,00",
    "length": 448,
    "copies": 1
  },
  {
    "title": "Introduction to Functional Programming Systems Using Haskell (Cambridge Computer Science Texts)",
    "image": "f28f982fc2900b260e40b37b28b95f62c4",
    "creators": "Antony J. T. Davie",
    "first_name": "Antony",
    "last_name": "Davie",
    "ean_isbn13": 9780521277242,
    "upc_isbn10": 521277248,
    "description": "Functional programming, is a style of programming that has become increasingly popular during the past few years. Applicative programs have the advantage of being almost immediately expressible as functional descriptions; they can be proved correct and transformed through the referential transparency property. This book presents the basic concepts of functional programming, using the language HASKELL for examples. The author incorporates a discussion of lambda calculus and its relationship with HASKELL, exploring the implications for parallelism.",
    "publisher": "Cambridge University Press",
    "publish_date": "1992-06-26",
    "notes": "",
    "price": "R$ 70,00",
    "length": 304,
    "copies": 1
  },
  {
    "title": "Technology Ventures From Idea to Enterprise",
    "image": "93fd730e95991db3d54e9204dba2804380",
    "creators": "Byers, Dorf, Nelson",
    "first_name": "Byers",
    "last_name": "Byers",
    "ean_isbn13": 9781259252754,
    "upc_isbn10": 1259252752,
    "description": "For business, engineering, and science students and professionals who demand a comprehensive guide to high-growth entrepreneurship, this title presents the resource for analyzing opportunities and building new enterprises.",
    "publisher": "McGrawHill Education",
    "publish_date": "2014-05-16",
    "notes": "",
    "price": "R$ 50,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Design of Everyday Things: Revised and Expanded Edition",
    "image": "lr5a706cf3ebc7bfe2a9399b4a8cd72120",
    "creators": "Don Norman",
    "first_name": "Don",
    "last_name": "Norman",
    "ean_isbn13": 9780465050659,
    "upc_isbn10": 465050654,
    "description": "Even the smartest among us can feel inept as we fail to figure out which light switch or oven burner to turn on, or whether to push, pull, or slide a door. The fault, argues this ingenious&mdash;even liberating&mdash;book, lies not in ourselves, but in product design that ignores the needs of users and the principles of cognitive psychology. The problems range from ambiguous and hidden controls to arbitrary relationships between controls and functions, coupled with a lack of feedback or other assistance and unreasonable demands on memorization. The Design of Everyday Things shows that good, usable design is possible. The rules are simple: make things visible, exploit natural relationships that couple function and control, and make intelligent use of constraints. The goal: guide the user effortlessly to the right action on the right control at the right time.In this entertaining and insightful analysis, cognitive scientist Don Norman hails excellence of design as the most important key to regaining the competitive edge in influencing consumer behavior. Now fully expanded and updated, with a new introduction by the author, The Design of Everyday Things is a powerful primer on how&mdash;and why&mdash;some products satisfy customers while others only frustrate them.",
    "publisher": "Basic Books",
    "publish_date": "2013-11-05",
    "notes": "",
    "price": "R$ 20,00",
    "length": 384,
    "copies": 1
  },
  {
    "title": "De Zero A Um (Em Portugues do Brasil)",
    "image": "m4646aa8d2cc74b59b5cb2d0b646903560",
    "creators": "Peter Thiel/Blake Masters",
    "first_name": "Peter",
    "last_name": "Masters",
    "ean_isbn13": 9788539006205,
    "upc_isbn10": 8539006200,
    "description": "Para Peter Thiel, cofundador do PayPal e investidor em diversas startups, como o Facebook, o proximo Bill Gates nao criara um sistema operacional. O proximo Larry Page ou Sergey Brin nao desenvolvera um mecanismo de busca. E o proximo Mark Zuckerberg nao criara uma rede social. Se voce esta copiando essas pessoas, nao esta aprendendo com elas. E mais facil copiar um modelo que criar algo novo. O progresso vem do monopolio, nao da competicao. Se voce faz o que nunca foi feito e consegue fazer melhor do que qualquer um, tem um monopolio e qualquer negocio so e bem-sucedido na medida em que e um monopolio. Mas quanto mais voce compete, mais se torna parecido com todo o resto. A competicao destroi os lucros dos individuos, das empresas e da sociedade como um todo.De zero a um: O que aprender sobre empreendedorismo com o Vale do Silicio nao oferece formula para o sucesso. O paradoxo de ensinar empreendedorismo e que tal formula nao pode existir. Como cada inovacao e unica, nenhuma autoridade consegue prescrever em termos concretos como ser inovador. Toda inovacao vai de 0 a 1. No livro, o autor revela como construir empresas que criem coisas novas. Apresenta uma visao otimista do futuro do progresso e uma maneira original de pensar sobre inovacao: ensina voce a fazer perguntas que o levem a encontrar valor em lugares inesperados.",
    "publisher": "Objetiva",
    "publish_date": "2014-01-01",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "InterWorld",
    "image": "128083f0200ae7fe3249940d163a99e700",
    "creators": "Neil Gaiman, Michael Reaves",
    "first_name": "Neil",
    "last_name": "Gaiman",
    "ean_isbn13": 9780062125309,
    "upc_isbn10": 62125303,
    "description": "When Newbery Medal winner Neil Gaiman and Emmy Award winner Michael Reaves teamed up, they created the bestselling YA novel InterWorld.&nbsp;InterWorld tells the story of Joey Harker, a very average kid who discovers that his world is only one of a trillion alternate earths. Some of these earths are ruled by magic. Some are ruled by science. All are at war.&nbsp;Joey teams up with alternate versions of himself from an array of these worlds. Together, the army of Joeys must battle evil magicians Lord Dogknife and Lady Indigo to keep the balance of power between all the earths stable. Teens&mdash;and tweens and adults&mdash;who obsessively read the His Dark Materials and Harry Potter series will be riveted by InterWorld and its sequel, The Silver Dream.",
    "publisher": "HarperTeen",
    "publish_date": "2013-04-23",
    "notes": "",
    "price": "R$ 20,00",
    "length": 304,
    "copies": 1
  },
  {
    "title": "The Silver Dream: An InterWorld Novel",
    "image": "gv802981a2884bb76226c0f84cfdd39ab5",
    "creators": "Neil Gaiman, Michael Reaves, Mallory Reaves",
    "first_name": "Neil",
    "last_name": "Gaiman",
    "ean_isbn13": 9780062262110,
    "upc_isbn10": 62262114,
    "description": "Sequel to New York Times bestseller INTERWORLD by award-winning writers Neil Gaiman and Michael Reaves. Joey Harker is a hero...After mastering the ability to walk between dimensions, Joey helped save the Altiverse from destruction. But rival powers of magic and science are still out there, seeking to control all worlds. InterWorld&#039;s peacekeeping mission is far from finished. And when a stranger follows Joey back to BaseTown things get even more complicated. No one knows who she is or where she&#039;s from and, more importantly, why she knows so much about InterWorld. Dangerous times lie ahead...",
    "publisher": "HarperTeen",
    "publish_date": "2013-04-23",
    "notes": "",
    "price": "R$ 20,00",
    "length": 256,
    "copies": 1
  },
  {
    "title": "The Ocean at the End of the Lane: A Novel",
    "image": "frc6fcbaf196c5acd304f337a08711ff51",
    "creators": "Neil Gaiman",
    "first_name": "Neil",
    "last_name": "Gaiman",
    "ean_isbn13": 9780062255655,
    "upc_isbn10": 62255657,
    "description": "A brilliantly imaginative and poignant fairy tale from the modern master of wonder and terror, The Ocean at the End of the Lane is Neil Gaiman&rsquo;s first new novel for adults since his #1 New York Times bestseller Anansi Boys. This bewitching and harrowing tale of mystery and survival, and memory and magic, makes the impossible all too real...",
    "publisher": "William Morrow",
    "publish_date": "2013-06-18",
    "notes": "",
    "price": "R$ 20,00",
    "length": 192,
    "copies": 1
  },
  {
    "title": "Belas maldições (Good Omens)",
    "image": "1db09a4d407a58d620cd1e409708cdbfda",
    "creators": 0,
    "first_name": 0,
    "last_name": 0,
    "ean_isbn13": 9788528606621,
    "upc_isbn10": 8528606627,
    "description": "Segundo as Belas e Precisas Profecias de Agnes Nutter, o mundo vai acabar num sábado. No próximo sábado, e ainda por cima antes do jantar! O que é um grande problema para os anjos Aziraphale, emissário do Céu, e seu colega Crowley, que na época de Adão ocupava o posto de Serpente do Paraíso. Eles precisam impedir o Apocalipse, porque a Terra é um ótimo lugar para se viver, pelo menos na opinião deles...Portanto, eles não têm outra alternativa senão encontrar e matar o Anticristo, a mais poderosa criatura do planeta. O problema é que o Anticristo tem onze anos e, ao contrário de tudo o que você já possa ter visto em algum filme, é um garoto que adora seu cachorro, se preocupa com o meio ambiente e é o filho que qualquer pai gostaria de ter. Além, claro, de ser indestrutível...Em Belas Maldições, Terry Pratchett e Neil Gaiman se uniram para criar uma engraçadíssima sátira a filmes como \"A Profecia\" e \"O Bebê de Rosemary\", num caldeirão que mistura personagens tão improváveis de se encontrar quanto tibetanos, alienígenas e os Quatro Motoqueiros do Apocalipse. Afinal, o que se poderia esperar nos anos noventa?[...]",
    "publisher": "Bertrand",
    "publish_date": "1999-01-01",
    "notes": "",
    "price": "R$ 20,00",
    "length": 374,
    "copies": 1
  },
  {
    "title": "Star Wars - Livro 1: O Caminho Jedi (Em Portugues do Brasil)",
    "creators": "Daniel Wallace",
    "first_name": "Daniel",
    "last_name": "Wallace",
    "ean_isbn13": 9788528617801,
    "upc_isbn10": 8528617807,
    "description": "O CAMINHO JEDIUm Manual Para Estudantes da ForcaDesvende os segredos e partilhe do conhecimento que educou e esclareceu geracoes de Jedi - da historia e hierarquia das Ordens Jedi a maestria da Forca e nuances do combate de sabre de luz.Passado de mao em mao de Mestre para Padawan, de Yoda e Obi-Wan Kenobi para Anakin e Luke Skywalker, este exemplar recebeu as anotacoes de cada Jedi que trocou e estudou suas paginas - adicionando suas experiencias pessoais e as licoes aprendidas. Este exemplar agora e entregue a voce.NOVOS PERSONAGENSNOVAS CRIATURASNOVAS NAVES",
    "publisher": "Bertrand Brasil",
    "publish_date": "2013-01-01",
    "notes": "Capa Dura",
    "price": "R$ 35,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Doctor Who. Quando Cair O Verão E Outras Histórias (Em Português do Brasil)",
    "image": "a44fdc5308232d30a3c067ca4eac3f9eed",
    "creators": "Amelia Williams",
    "first_name": "Amelia",
    "last_name": "Williams",
    "ean_isbn13": 9788581052250,
    "upc_isbn10": 8581052258,
    "description": "Doctor Who: Quando cair o verão e outras histórias é um livro de contos inspirados em episódios da série britânica Doctor Who, que em novembro de 2013 completou 50 anos no ar. A obra reúne três contos: Quando cair o verão, de Amelia Williams; O Beijo do Anjo, de Melody Malone; e O Demônio na fumaça, narrado pelo Sr. Justin Richards. O livro traz ainda uma rara entrevista com Amelia Williams, a reclusa autora de A garota que nunca cresceu, e uma nova introdução escrita por ela. Inspirado no episódio The Bells of Saint John, Quando cair o verão narra a história da jovem Kate, que passa suas férias na vila litorânea de Watchcombe e está determinada a aproveitar ao máximo sua última semana de folga. No entanto, ao descobrir uma misteriosa pintura chamada \"O Senhor do Inverno\", ela viverá aventuras que jamais poderia ter imaginado. Em O Beijo do Anjo, inspirado em The Angels Take Manhattan, a detetive particular Melody Malone recebe uma visita inesperada: o astro de cinema Rock Railton. Ele acredita que alguém quer matá-lo e, quando menciona \"o beijo do anjo\", Melody aceita o caso. E com o passar do tempo, a detetive logo descobre que o preço da fama é maior do que ela poderia imaginar. Narrado por Justin Richards e inspirado pelo episódio The Snowmen, O Demônio na fumaça, é um thriller no qual dois garotinhos, cansados de limpar a neve do pátio do orfanato, decidem fazer um boneco de neve - e se deparam com um mistério brutal. Fascinados e horrorizados, testemunham quando o boneco de neve começa a sangrar. A busca por respostas levará Harry, um dos meninos, à aventura mais perigosa e empolgante de sua vida.[...]",
    "publisher": "Suma de Letras",
    "publish_date": "2014-01-01",
    "notes": "",
    "price": "R$ 15,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Doctor Who: O Prisioneiro dos Daleks",
    "creators": "Trevor Baxendale",
    "first_name": "Trevor",
    "last_name": "Baxendale",
    "ean_isbn13": 9788581052847,
    "upc_isbn10": 8581052843,
    "description": "O Imperio Dalek nao para de se expandir, e batalhas eclodem em varios sistemas solares. Quando o futuro da galaxia esta em jogo, o Doutor se ve a bordo de uma nave proxima a linha de frente, junto a um implacavel grupo de cacadores de recompensas.O Comando da Terra paga a eles por cada Dalek morto, por cada olho entregue como prova. Mas, com a ajuda do Doutor, os cacadores conseguem algo de valor inestimavel: um Dalek inteiro, vivo, com os sistemas desarmados e pronto para ser interrogado. No entanto, com os Daleks nada e o que parece e ninguem esta a salvo. Quando o jogo virar, como o Doutor sobrevivera ao se tornar prisioneiro de seu maior inimigo?",
    "publisher": "SUMA DE LETRAS - GRUPO OBJETIVA",
    "publish_date": "2015-01-01",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Star Trek: Portal do Tempo",
    "image": "gge4880bfdd04ad96e6eac991e6e77c48b",
    "creators": "A. C. Crispin",
    "first_name": "A.",
    "last_name": "Crispin",
    "ean_isbn13": 9788576572640,
    "upc_isbn10": 8576572648,
    "description": "",
    "publisher": "ALEPH",
    "publish_date": "2016-01-01",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Poder (Em Portugues do Brasil)",
    "creators": "Naomi Alderman",
    "first_name": "Naomi",
    "last_name": "Alderman",
    "ean_isbn13": 9788542212976,
    "upc_isbn10": 8542212975,
    "description": "O que você faria se tivesse o poder em suas mãos? \"Jogos vorazes encontra o conto da aia.\" COSMOPOLITAN Em um futuro próximo, as mulheres desenvolvem um estranho poder: elas se tornam capazes de eletrocutar outras pessoas, infligindo dores terríveis. Até a morte. De repente, os homens se dão conta de que não estão mais no controle do mundo. \"Um olhar fascinante no que o mundo poderia ter se tornado se o sexismo dos últimos milênios tivesse tomado rumos diferentes. Engenhoso. Merece ser lido por todas as mulheres (e, claro, por todos os homens).\" THE TIMES \"O poder é uma leitura explosiva.\" FINANCIAL TIMES \"Um romance envolvente, que nos obriga a encarar uma distopia que já existe. E que está entre nós há séculos.\" MICHAEL SCHAUB, NPR.",
    "publisher": "",
    "publish_date": "",
    "notes": "Capa Dura",
    "price": "R$ 25,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Novo Iluminismo. Em Defesa da Razao da Ciencia e do Humanismo (Em Portugues do Brasil)",
    "image": "bxf744282811dee0ffdc1b99c0402ae8cf",
    "creators": "Steven Pinker",
    "first_name": "Steven",
    "last_name": "Pinker",
    "ean_isbn13": 9788535931440,
    "upc_isbn10": 978853593144,
    "description": "Com profundidade analítica e talento literário, Steven Pinker defende a razão, a ciência e o humanismo, os ideais de que precisamos para enfrentar os nossos problemas e dar continuidade ao nosso progresso.Em O novo Iluminismo , uma original avaliação da condição humana no terceiro milênio, o cientista cognitivo Steven Pinker nos incita a rechaçar manchetes alarmistas e profecias apocalípticas, que vicejam nos dias atuais e influenciam nossa visão de mundo. Com 75 gráficos impressionantes, ele demostra que a vida, a saúde, a prosperidade, a segurança, a paz, o conhecimento e a felicidade estão em ascensão, não apenas no Ocidente, mas em todo o mundo. Para Pinker, esse progresso é uma herança do Iluminismo: a convicção de que a razão e a ciência podem impulsionar o florescimento humano - e, mais do que nunca, elas precisam de uma defesa vigorosa. Nadando contra as correntes da natureza humana exploradas por demagogos - tribalismo, autoritarismo, demonização, pensamento mágico -, o projeto iluminista é atacado por religiosos, políticos e intelectuais pessimistas que insistem que a civilização ocidental passa por um inexorável processo de declínio. Mas basta olhar os dados: eles indicam que, com o avanço do conhecimento, as pessoas estão de fato vivendo mais e melhor. Sem negar que nossos tempos são atribulados, Steven Pinker não hesita em apontar o caminho para as soluções: reforçar o ideal iluminista de usar a razão e a ciência para resolver problemas.\"A mente de Steven Pinker ostenta uma inteligência aguda, um conhecimento profundo e uma enorme solidariedade humana.\" - Richard Dawkins\"Um livro excepcional, escrito com lucidez e na hora certa, repleto de dados que sustentam uma eloquente defesa do humanismo racional.\" - The New York Times Book Review",
    "publisher": "",
    "publish_date": "",
    "notes": "",
    "price": "R$ 35,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Silmarillion, O",
    "image": "j527f6a266ea323f4734bce801a55533b8",
    "creators": "J.R.R. Tolkien",
    "first_name": "J.R.R.",
    "last_name": "Tolkien",
    "ean_isbn13": 9788533611658,
    "upc_isbn10": "853361165X",
    "description": "",
    "publisher": "Martins Fontes",
    "publish_date": "",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Fim da Infancia (Em Portugues do Brasil)",
    "image": "00daeb932dcf9adc13393b7df0dd07149d",
    "creators": "Arthur C. Clarke",
    "first_name": "Arthur",
    "last_name": "Clarke",
    "ean_isbn13": 9788576570813,
    "upc_isbn10": 8576570815,
    "description": "Em plena Guerra Fria, enquanto russos e americanos se preparam para a corrida espacial, imensas naves surgem sobre as principais capitais do mundo, revelando um dos grandes misterios da humanidade: O homem nao esta sozinho no universo.Seus ocupantes, chamados de Senhores Supremos, dominam a Terra de forma pacifica e melhoram substancialmente as condicoes de vida. A ignorancia, a guerra e a pobreza deixam de existir, dando inicio a uma era de ouro. Porem, uma duvida assombra a humanidade: quais seriam os verdadeiros objetivos dos Senhores Supremos? Ate quando suas politicas iriam coincidir com o bem-estar dos homens? As respostas para essas questoes podem revelar uma verdade aterradora.",
    "publisher": "Aleph",
    "publish_date": "2010-01-01",
    "notes": "",
    "price": "R$ 15,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Star Wars: Jedi Academy",
    "image": "7jce0d55527f78d92a7a56c77af76c2b61",
    "creators": "Jeffrey Brown",
    "first_name": "Jeffrey",
    "last_name": "Brown",
    "ean_isbn13": 9780545505178,
    "upc_isbn10": 545505178,
    "description": "New York Times bestselling author/illustrator Jeffrey Brown takes readers to a middle school in a galaxy far, far away....This incredible, original story captures all of the humor, awkwardness, fun, and frustrations of middle school--all told through one boy&#039;s comics, journal entries, letters, doodles, and newspaper clippings. The setting? A galaxy far, far away...Roan&#039;s one dream is to leave home and attend Pilot Academy like his older brother, father, and grandfather. But just as Roan is mysteriously denied entrance to Pilot School, he is invited to attend Jedi Academy--a school that he didn&#039;t apply to and only recruits children when they are just a few years old. That is, until now...This inventive novel follows Roan&#039;s first year at Jedi Academy where, under the tutelage of Master Yoda, he learns that he possesses more strength and potential than he could have ever dreamed. Oh, and he learns other important things too--like how to make a baking soda volcano, fence with a lightsaber, slow dance with a girl, and lift boulders with the Force.",
    "publisher": "Scholastic Inc.",
    "publish_date": "2013-08-27",
    "notes": "Capa Dura",
    "price": "R$ 30,00",
    "length": 160,
    "copies": 1
  },
  {
    "title": "Hobbit - Edicao 4 (Em Portugues do Brasil)",
    "image": "bj00a83176a05611faf8afdb8b48d488e8",
    "creators": "J. R. R. Tolkien",
    "first_name": "J.",
    "last_name": "Tolkien",
    "ean_isbn13": 9788578273873,
    "upc_isbn10": 8578273877,
    "description": "E impossivel transmitir ao novo leitor todas as qualidades e o alcance do livro. Alternadamente comica, singela, epica, monstruosa e diabolica, a narrativa desenvolve-se em meio a inumeras mudancas de cenarios e de personagens, num mundo imaginario absolutamente convincente em seu detalhes. Nas palavras do romancista Richard Hughes, &quot;quanto a amplitude imaginativa, a obra praticamente nao tem paralelos e e quase igualmente notavel na sua vividez e na habilidade narrativa, que mantem o leitor preso pagina apos pagina&quot;. Tolkien criou em O Senhor dos aneis uma nova mitologia, num mundo inventado que demonstrou possuir um poder de atracao atemporal.",
    "publisher": "Wmf Martins Fontes",
    "publish_date": "2011-01-01",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Os Despossuídos (Em Português do Brasil)",
    "image": "k8d15773cb71be0da75d9fa33ef3a48b3c",
    "creators": "Ursula K. Le Guin",
    "first_name": "Ursula",
    "last_name": "Guin",
    "ean_isbn13": 9788576573685,
    "upc_isbn10": 8576573687,
    "description": "Ganhador do prêmio Nebula de melhor romance em 1974, além do Hugo e do Locus em 1975, Os Despossuídos lida com temas fundamentais a sua época, como o capitalismo, o comunismo russo e o anarquismo, além dos conceitos de individual e coletivo. O romance se passa em dois planetas-gêmeos, Uras e Anarres, com sistemas políticos opostos e prestes a entrar em guerra, numa alusão à Guerra Fria.",
    "publisher": "Aleph",
    "publish_date": "2017-01-01",
    "notes": "",
    "price": "R$ 35,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Fontes do Paraiso, As",
    "image": "lg1226e6420cb365f81b3f2a4aa3f6341f",
    "creators": "Arthur C. Clarke",
    "first_name": "Arthur",
    "last_name": "Clarke",
    "ean_isbn13": 9788576571827,
    "upc_isbn10": "857657182X",
    "description": "Há dois séculos, Kalidasa desafiou sua família e sua religião para empreender uma verdadeira maravilha arquitetônica: a construção de um suntuoso palácio no topo de uma montanha, que o alçaria aos céus e o igualaria aos deuses. Duzentos anos depois, o ambicioso engenheiro Vannevar Morgan, que já unira dois continentes com a Ponte Gibraltar, se propõe a construir uma nova ponte, desta vez ligando a Terra ao espaço sideral. O que ele não imagina, porém, é que em seu caminho está um monastério budista, localizado sobre a única montanha na qual seu projeto poderia ser construído. Em paralelo, a humanidade detecta um estranho sinal de rádio, de origem não humana. Pela primeira vez na história, o planeta Terra é contatado por uma raça alienígena que, ao que tudo indica, está cada vez mais próxima.[...]",
    "publisher": "ALEPH",
    "publish_date": "2015-01-01",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O tempo desconjuntado (Em Portugues do Brasil)",
    "image": "4r8fd96c38bd2b9387e4e297d7146a3114",
    "creators": "Philip K. Dick",
    "first_name": "Philip",
    "last_name": "Dick",
    "ean_isbn13": 9788556510662,
    "upc_isbn10": 8556510663,
    "description": "Um romance impressionante de um dos maiores nomes da ficção científica. Philip K. Dick faz o leitor duvidar do real e se perguntar a todo momento até que ponto a paranoia é justificada. Com edição especial em capa dura e projeto gráfico arrojado, uma obra inédita de Philip K. Dick chega ao Brasil, trazendo um retrato único da construção do medo, da desconfiança e da própria realidade. Ragle Gumm tem um trabalho bastante peculiar: ele sempre acerta a resposta para um concurso diário do jornal local. E quando ele não está consultando seus gráficos e tabelas para o trabalho, ele aproveita a vida tranquila em uma pequena cidade americana em 1959. Pelo menos, é isso que ele acha. Mas coisas estranhas começam a acontecer. Primeiro, Ragle encontra uma lista telefônica e todos os números parecem ter sido desconectados. Depois, uma revista sobre famosos traz na capa uma mulher belíssima que ele nunca tinha visto antes, Marilyn Monroe. E para piorar, objetos do dia a dia começam a desaparecer e são substituídos por pedaços de papel com palavras escritas, como \"vaso de flores\" e \"barraca de refrigerante\". A única alternativa que Ragle encontra para descobrir o que está acontecendo é fugir da cidade e de todos esses acontecimentos bizarros, contudo, nem a fuga nem a descoberta serão tão fáceis quanto ele imaginava. \"Maravilhoso, terrivelmente divertido, ainda mais se você já considerou a possibilidade do mundo ser um universo fictício construído somente para impedir que você descubra quem realmente é. Uma possibilidade bastante plausível, claro.\" - Rolling Stone .",
    "publisher": "Suma de Letras",
    "publish_date": "2018-01-01",
    "notes": "Capa Dura",
    "price": "R$ 25,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Reflexo na Escuridao, Um",
    "image": "e7e5eabdc3bcd8f855dd1e2f9403975fd1",
    "creators": "Philip K. Dick",
    "first_name": "Philip",
    "last_name": "Dick",
    "ean_isbn13": 9788576573074,
    "upc_isbn10": 8576573075,
    "description": "Fred, um agente disfarçado, é obrigado a esconder sua verdadeira identidade tanto dos que convivem com ele no dia a dia dos usuários de substâncias ilícitas quanto de seus colegas policiais. No entanto, trabalhar como agente infiltrado para a divisão de narcóticos pode cobrar seu preço: ele acaba viciado em uma droga psicotrópica perigosa e muitas vezes letal, a Substância D. Um dos mais terríveis efeitos colaterais da substância é a cisão entre os dois hemisférios do cérebro, que passam a agir de forma independente, por vezes até \"competitiva\" entre si. Ambas as identidades, a de viciado e a de policial, podem levar o protagonista aos limites entre a realidade e a ilusão, onde paira a dúvida a respeito do verdadeiro \"eu\".",
    "publisher": "Aleph",
    "publish_date": "2016-01-01",
    "notes": "",
    "price": "R$ 25,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Realidades Adaptadas",
    "image": "nlddeac3655d6e671e1fac8bf3f718f926",
    "creators": "Philip K. Dick",
    "first_name": "Philip",
    "last_name": "Dick",
    "ean_isbn13": 9788576571346,
    "upc_isbn10": "857657134X",
    "description": "&#039;Realidades Adaptadas&#039; re&uacute;ne os contos de Philip K. Dick que foram adaptados para o cinema - &#039;O Vingador do Futuro&#039;, &#039;Minority Report&#039;, &#039;Os Agentes do Destino&#039;, &#039;O Pagamento&#039;, &#039;Impostor&#039;, &#039;O Vidente&#039; e &#039;Screamers&#039;.",
    "publisher": "",
    "publish_date": "",
    "notes": "",
    "price": "R$ 25,00",
    "length": 304,
    "copies": 1
  },
  {
    "title": "Star Wars - Livro 2: Livro dos Sith (Em Portugues do Brasil)",
    "image": "2j8ca67bb4b0e9c65ff17381c02b272fb6",
    "creators": "Daniel Wallace",
    "first_name": "Daniel",
    "last_name": "Wallace",
    "ean_isbn13": 9788528617931,
    "upc_isbn10": 8528617939,
    "description": "Ao longo dos seculos, a medida que os Lordes Sith ascendiam ao poder, alguns deles registravam sua filosofia e seus esquemas para assumir o controle da galaxia. Ao serem derrotados, esse conhecimento desapareceu. Ou, pelo menos, era o que parecia. Seus escritos foram passados entre Sith selecionados - e ate mesmo Jedi -, que acrescentaram suas reflexoes a essas raras paginas. Na busca por dominio, Darth Sidious foi atras do que sobrou dos cinco textos mais lendarios do lado negro. A partir desse conhecimento, ele escreveu um sexto texto - seu proprio manifesto. Reunidos, esses documentos formam o Livro dos Sith.Nele sao apresentados os maiores mestres, o surgimento do cla, os armamentos, o vestuario, os segredos obscuros, entre outros.",
    "publisher": "Bertrand Brasil",
    "publish_date": "2013-01-01",
    "notes": "Capa Dura",
    "price": "R$ 35,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Histories of Middle Earth, Volumes 1-5",
    "image": "p109dabf1ce7c63a4d41612749bd29bc82",
    "creators": "J.R.R. Tolkien",
    "first_name": "J.R.R.",
    "last_name": "Tolkien",
    "ean_isbn13": 9780345466457,
    "upc_isbn10": 345466454,
    "description": "The Histories of Middle-Earth series is 5 softcovers in slipcase from the author of The Hobit. J.R.R. Tolkien wrote a vast fictional history of Middle-Earth, and the first five volumes of the Histories are compiled here.",
    "publisher": "Del Rey",
    "publish_date": "2003-08-26",
    "notes": "Box",
    "price": "R$ 200,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Business Model Generation. Inova&ccedil;&atilde;o Em Modelos De Neg&oacute;cios (Em Português do Brasil)",
    "image": "82f2b4210634979e81eb8e6f7acec002ac",
    "creators": "Alexander Osterwalder",
    "first_name": "Alexander",
    "last_name": "Osterwalder",
    "ean_isbn13": 9788576085508,
    "upc_isbn10": "857608550X",
    "description": "Se sua organiza&ccedil;&atilde;o precisa de uma estrat&eacute;gia para chegar na frente de seus concorrentes, voc&ecirc; precisa do BMG. &quot;O ambiente digital demanda uma nova forma de olhar os neg&oacute;cios de m&iacute;dia. O BMG &eacute; a ferramenta que escolhemos para nos ajudar a navegar melhor nesse mundo convergente.&quot; - Jorge N&oacute;brega, diretor-geral de Gest&atilde;o Corporativa das Organiza&ccedil;&otilde;es Globo.[...]",
    "publisher": "Alta Books",
    "publish_date": "",
    "notes": "",
    "price": "R$ 40,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Gata Garota - Volume 1 (Em Portugues do Brasil)",
    "creators": "Fefe Torquato",
    "first_name": "Fefe",
    "last_name": "Torquato",
    "ean_isbn13": 9788582861356,
    "upc_isbn10": 8582861354,
    "description": "Gigi e uma garota que passa metade do seu tempo dormindo, a outra metade comendo e o dia inteiro entediada. Por que alguem se interessaria pela sua vida? Porque Gigi e metade gato. Ela descende de uma familia de gatos-gente, unicos de sua especie, ate onde se sabe Criaturas fascinantes, que sabem o poder que exercem sobre os humanos e, por isso, dominam o mundo com seu pelo macio, olhar penetrante de desdem e eventual pose controversa. Neste volume, Gigi enfrenta problemas cotidianos, como roubar assentos alheios, torturar insetos por horas, conviver com a lider da familia, Fefe que pode ou nao estar enlouquecendo e com o ciume de seu namorado, Danilo, que desconfia nao ser o unico. Pare o que estiver fazendo e leia esta serie. Tem gatos.",
    "publisher": "Nemo",
    "publish_date": "2015-01-01",
    "notes": "Autografado",
    "price": "R$ 25,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Vertigo - Contos Macabros",
    "image": "jh12b16d3b90b48bd1b85b3797e274f497",
    "creators": "Grant Morrison",
    "first_name": "Grant",
    "last_name": "Morrison",
    "ean_isbn13": 9788589961790,
    "upc_isbn10": 8589961796,
    "description": "",
    "publisher": "Opera Graphica",
    "publish_date": "1905-01-01",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Kick-Ass",
    "image": "828dbc3bd50521513db4ea5ecb4516ef",
    "creators": "Mark Millar, John Romita Jr.",
    "first_name": "Mark",
    "last_name": "Millar",
    "ean_isbn13": 9780785132615,
    "upc_isbn10": 785132619,
    "description": "The book that started the worldwide phenomenon is finally available in softcover! KICK-ASS is back, in time to celebrate the DVD release of the movie and the launch of KICK-ASS 2: BALLS TO THE WALL! KICK-ASS is the NEW YORK TIMES bestselling graphic novel that spent three months at the top spot on the Diamond Direct Market Charts and spawned the movie that opened at number one in the box office! Kick-Ass and Hit-Girl's origins are here under one cover! Relive--or experience for the first time--what happens when teenager Dave Lizewski asks himself, \"How come nobody's ever become a superhero before?\" Superstar creators MARK MILLAR and JOHN ROMITA JR. have created a true 21st century classic. When your grandchildren ask you where you were when KICK-ASS came out, you'll want to be able to look them in the eye and tell them the truth: you were reading this paperback! Collecting KICK-ASS #1-8.",
    "publisher": "Marvel Enterprises",
    "publish_date": "2011-07-20",
    "notes": "Capa Dura",
    "price": "R$ 45,00",
    "length": 192,
    "copies": 1
  },
  {
    "title": "O Universo de Sandman. O Sonhar - Volume 2 (Em Portugues do Brasil)",
    "image": "24ab6203360f9fe5d775b98a5d85bd019d",
    "creators": "Simon Spurrier",
    "first_name": "Simon",
    "last_name": "Spurrier",
    "ean_isbn13": 9788542628456,
    "upc_isbn10": 8542628454,
    "description": "",
    "publisher": "",
    "publish_date": "2019-01-01",
    "notes": "",
    "price": "R$ 15,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Universo De Sandman - Lucifer Volume 1 (Em Portugues do Brasil)",
    "image": "ll07e2d53ca59eca6d3b11428a3a441174",
    "creators": "Neil Gaiman",
    "first_name": "Neil",
    "last_name": "Gaiman",
    "ean_isbn13": 9788542621396,
    "upc_isbn10": 8542621395,
    "description": "",
    "publisher": "",
    "publish_date": "",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Universo de Sandman. O Sonhar - Volume 1 (Em Portugues do Brasil)",
    "image": "5pa28e709bc4f69a3c96e6e520de4169ba",
    "creators": "Simon Spurrier",
    "first_name": "Simon",
    "last_name": "Spurrier",
    "ean_isbn13": 9788542621464,
    "upc_isbn10": 8542621468,
    "description": "",
    "publisher": "",
    "publish_date": "",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Fabulosos X-men, Os : O Bom, O Mau E O Inumano",
    "creators": "Bendis Bachalo",
    "first_name": "Bendis",
    "last_name": "Bachalo",
    "ean_isbn13": 9788542605570,
    "upc_isbn10": 8542605578,
    "description": "",
    "publisher": "",
    "publish_date": "",
    "notes": "Capa Dura",
    "price": "R$ 15,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Universo X - Volume 1 (Em Português do Brasil)",
    "image": "mk81ff94130f7703beead06bf5db6180e2.jpg",
    "creators": "Alex Ross",
    "first_name": "Alex",
    "last_name": "Ross",
    "ean_isbn13": 9788573517804,
    "upc_isbn10": 8573517808,
    "description": "A Terra está em estado de guerra civil. A morte do embrião celestial no núcleo do planeta levou à repolarização do planeta, ameaçando extinguir a humanidade. Paralelamente, a população alterada pela ação das névoas terrígenas dos Inumanos insurge-se contra seus ex-protetores, os super-heróis, que desejam reverter as mutações eliminando as névoas da Terra com a ajuda das Tochas Humanas de Reed Richards. Em meio ao caos, uma figura sinistra parece manipular os eventos para atingir seus próprios objetivos. Os premiados idealizadores de Terra X, Alex Ross e Jim Krueger, estão de volta no segundo capítulo da trilogia que vislumbra o sombrio futuro do Universo Marvel, numa luxuosa edição com mais de 700 páginas, apresentando o talento de ilustradores como Doug Braithwaite, Bill Reinhold, Brent Anderson, Butch Guice, John Romita, Tom Yeates, John Totleben e outros. Não perca. (Universe X 0-12; Universe X: 4; Universe X: Spidey; Universe X: Cap; Universe X: X; Universe X: Beasts; Universe X: Iron Men; Universe X: Omnibus).",
    "publisher": "Panini",
    "publish_date": "2012-01-01",
    "notes": "Capa Dura",
    "price": "R$ 100,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Multiverso",
    "creators": "Grant Morrison, Ivan Reis, Joe Prado",
    "first_name": "Grant",
    "last_name": "Morrison",
    "ean_isbn13": 9788583682110,
    "upc_isbn10": 8583682119,
    "description": "Existem mundos que vocês nunca imaginou... Mundos além daqueles que você conhece. Mundos onde heróis lutam pela verdade e pela justiça. Mundos onde a escuridão reina, e apenas alguns poucos escolhidos mantêm a luz viva. Mundos de magia e ciência, comédia e tragédia, monstros e maravilhas. Cinquenta e dois mundos. Possibilidades infinitas. E uma ameaça grande o suficiente para destruir todas elas. Esse é o Multiverso. E o genial Grant Morrison - ao lado da nata dos artistas da DC Comics - vai levar o leitor brasileiros em uma tour repleta de emoção e conceitos revolucionários por esse território às vezes hostil, mas sempre intrigante!",
    "publisher": "",
    "publish_date": "",
    "notes": "Capa Dura",
    "price": "R$ 250,00",
    "length": 484,
    "copies": 1
  },
  {
    "title": "Batman: The Return of Bruce Wayne",
    "image": "3mc57c99e4eb7aa370bfb455a484355d5f",
    "creators": "Grant Morrison",
    "first_name": "Grant",
    "last_name": "Morrison",
    "ean_isbn13": 9781401233822,
    "upc_isbn10": 1401233821,
    "description": "A time-spanning graphic novel featuring Bruce Wayne's return to Gotham City to take back the mantle of Batman written byaward-winning writer Grant Morrison and illustrated by a stable to today's hottest artists including Chris Sprouse, Frazer Irvingand Yannick Paquette. This is the final chapter of the epic storyline that began in the best-selling graphic novels, BATMAN:R.I.P. and FINAL CRISIS where the original Batman was lost in time after being bombarded with the omega beams of evil Des-pot,Darkseid and continued in BATMAN & ROBIN: BATMAN REBORN where Dick Grayson, the original Robin, tookover wearing the cape and cowl of the Dark Knight after the world's heroes believed his mentor to have died.",
    "publisher": "DC Comics",
    "publish_date": "2012-01-10",
    "notes": "",
    "price": "R$ 45,00",
    "length": 232,
    "copies": 1
  },
  {
    "title": "Dexter: A Mao Esquerda de Deus (Em Portugues do Brasil)",
    "creators": "Jeff Lindsay",
    "first_name": "Jeff",
    "last_name": "Lindsay",
    "ean_isbn13": 9788576653455,
    "upc_isbn10": 8576653451,
    "description": "Dexter Morgan e um educado lobo vestido em pele de ovelha. Ele e atraente e charmoso, mas algo em seu passado fez com que se transformasse numa pessoa diferente. Dexter e um serial killer. Na verdade, e um assassino incomum que extermina apenas aqueles que merecem. Ao mesmo tempo, trabalha como perito da policia de Miami... Em Dexter, a Mao Esquerda de Deus, o livro que deu origem a aclamada serie de TV, o adoravel matador depara-se com um concorrente de estilo semelhante ao seu, encanta-se e incomoda-se com ele, preve seus passos... A escrita requintada de Jeff Lindsay nos faz mergulhar na mente de um dos personagens mais ambiguos da historia da literatura de suspense. Nunca o macabro foi tratado com tanto refinamento e leveza. Dexter Morgan e uma obra-prima.",
    "publisher": "Planeta do Brasil",
    "publish_date": "2008-01-01",
    "notes": "",
    "price": "R$ 8,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Para onde vamos?",
    "creators": "Isaac Asimov",
    "first_name": "Isaac",
    "last_name": "Asimov",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "FC Hemus",
    "publish_date": "1979-01-01",
    "notes": "Capa Rasgada",
    "price": "R$ 0,00",
    "length": 373,
    "copies": 1
  },
  {
    "title": "Box Trilogia SPRAWL: Neuromancer + Count Zero + Mona Lisa Overdrive",
    "creators": "William Gibson",
    "first_name": "William",
    "last_name": "Gibson",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "No futuro, existe a matrix. Uma espécie de alucinação coletiva digital na qual a humanidade se conecta para, virtualmente, saber de tudo sobre tudo. Mas há uma elite que navega por essa grande rede de informação - os cowboys. Case era um deles, até o dia em que tentou ser mais esperto do que os seus patrões. Que fritaram suas conexões com o ciberespaço, tornando-o um pária entre os seus iguais. Ele vaga pelos subúrbios de Tóquio, mais envolvido do que nunca em destruir a si próprio, até ser contatado por Molly, uma bela e perigosa mulher que, assim como ele, desconfia de tudo e de todos. Os dois acabam se envolvendo numa missão cheia de mistérios e perigos. Esta edição comemorativa de 25 anos de 'Neuromancer' conta com nova tradução de Fábio Fernandes e prefácio de William Gibson. O romance de estréia de Gibson é o primeiro volume da chamada 'Trilogia do Sprawl', que ainda inclui os livros 'Count Zero' e 'Mona Lisa Overdrive'.",
    "publisher": "Aleph",
    "publish_date": "2001-01-01",
    "notes": "Box",
    "price": "R$ 60,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Romance da Ciência",
    "creators": "Carl Sagan",
    "first_name": "Carl",
    "last_name": "Sagan",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Editora Francisco Alves",
    "publish_date": "",
    "notes": "",
    "price": "R$ 8,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Box Coringa e Batman - A Piada Mortal - Edição Especial Limitada",
    "image": "fw1bc8f85f96d363a0df742f87f11d96dc",
    "creators": "Allan Moore, Brian Azarello",
    "first_name": "Allan",
    "last_name": "Moore",
    "ean_isbn13": 9788583681441,
    "upc_isbn10": 8583681449,
    "description": "",
    "publisher": "Panini Brasil",
    "publish_date": "",
    "notes": "Box - Capa Dura",
    "price": "R$ 100,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Odisséia Cósmica",
    "creators": "Jim Starlin",
    "first_name": "Jim",
    "last_name": "Starlin",
    "ean_isbn13": 9788573514315,
    "upc_isbn10": "",
    "description": "",
    "publisher": "Panini Brasil",
    "publish_date": "2007-01-01",
    "notes": "",
    "price": "R$ 45,00",
    "length": 200,
    "copies": 1
  },
  {
    "title": "Batman: Ano 100 Volume 2",
    "creators": "Paul Pope, Jose Villarrubia",
    "first_name": "Paul",
    "last_name": "Pope",
    "ean_isbn13": "",
    "upc_isbn10": 8573513608,
    "description": "",
    "publisher": "Panini Brasil",
    "publish_date": "2006-01-01",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Batman: Ano 100 Volume 1",
    "creators": "Paul Pope, Jose Villarrubia",
    "first_name": "Paul",
    "last_name": "Pope",
    "ean_isbn13": "",
    "upc_isbn10": 8573513608,
    "description": "",
    "publisher": "Panini Brasil",
    "publish_date": "2006-01-01",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Batman - A Queda do Morcego - Volume 1: Herói Quebrado",
    "creators": "Chuck Dixon, Doug Moench, Dorival Vitor Lopes, Edu Tanaka, Jim Aparo, Norm Breyfogle, Fabiano Denardin",
    "first_name": "Chuck",
    "last_name": "Dixon",
    "ean_isbn13": 9788573515039,
    "upc_isbn10": "",
    "description": "",
    "publisher": "Panini Brasil",
    "publish_date": "2008-01-01",
    "notes": "",
    "price": "R$ 45,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "RED Aposentados e Perigosos",
    "creators": "Warren Ellis, Cully Hamner",
    "first_name": "Warren",
    "last_name": "Ellis",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Panini Brasil",
    "publish_date": "2010-01-01",
    "notes": "",
    "price": "R$ 8,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Cerco",
    "creators": "Brian Michael Bendis, Olivier Coipel",
    "first_name": "Brian",
    "last_name": "Bendis",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Salvat",
    "publish_date": "2017-01-01",
    "notes": "Capa Dura",
    "price": "R$ 40,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Inescrito: Apocalipse Vol. 1 - Histórias de Guerra",
    "creators": "Mike Carey, Peter Gross",
    "first_name": "Mike",
    "last_name": "Carey",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Panini Brasil",
    "publish_date": "2015-07-01",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "O Inescrito: Apocalipse Vol. 2 - A Jornada",
    "creators": "Mike Carey, Peter Gross",
    "first_name": "Mike",
    "last_name": "Carey",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Panini Brasil",
    "publish_date": "2015-11-01",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Lúcifer: Céu Congelado",
    "creators": "Holly Black, Lee Garbett, Stephanie Hans, Antonio Fabela",
    "first_name": "Holly",
    "last_name": "Black",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Panini Brasil",
    "publish_date": "2017-12-01",
    "notes": "",
    "price": "R$ 20,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "John Constantine, Hellblazer – O Mago que Ri",
    "creators": "Andy Diggle, Leonardo Manco, Danijel Zezelj",
    "first_name": "Andy",
    "last_name": "Diggle",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Panini Brasil",
    "publish_date": "2015-01-01",
    "notes": "",
    "price": "R$ 40,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Sandman Overture 1",
    "creators": "Neil Gaiman, J. H. Williams III",
    "first_name": "Neil",
    "last_name": "Gaiman",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Vertigo Comics",
    "publish_date": "2013-12-01",
    "notes": "",
    "price": "R$ 30,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Sandman Overture 2",
    "creators": "Neil Gaiman, J. H. Williams III",
    "first_name": "Neil",
    "last_name": "Gaiman",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Vertigo Comics",
    "publish_date": "2014-05-01",
    "notes": "",
    "price": "R$ 30,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Sandman Overture 3",
    "creators": "Neil Gaiman, J. H. Williams III",
    "first_name": "Neil",
    "last_name": "Gaiman",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Vertigo Comics",
    "publish_date": "2014-09-01",
    "notes": "",
    "price": "R$ 30,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "Vingadores Secretos - Missão Marte",
    "creators": "Ed Braubaker, Mike Deodato",
    "first_name": "Ed",
    "last_name": "Braubaker",
    "ean_isbn13": "",
    "upc_isbn10": "",
    "description": "",
    "publisher": "Salvat",
    "publish_date": "",
    "notes": "Capa Dura",
    "price": "R$ 30,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Structure and Dynamics of Organizations and Groups",
    "creators": "Eric Berne",
    "first_name": "Eric",
    "last_name": "Berne",
    "ean_isbn13": 9780394170480,
    "upc_isbn10": 394170482,
    "description": "",
    "publisher": "",
    "publish_date": "",
    "notes": "",
    "price": "R$ 10,00",
    "length": "",
    "copies": 1
  },
  {
    "title": "The Startup Owner's Manual: The Step-By-Step Guide for Building a Great Company",
    "image": "gl9d0805abe060def29b388a3ab4a46e21",
    "creators": "Steve Blank, Bob Dorf",
    "first_name": "Steve",
    "last_name": "Blank",
    "ean_isbn13": 9780984999309,
    "upc_isbn10": 984999302,
    "description": "More than 100,000 entrepreneurs rely on this book for detailed, step-by-step instructions on building successful, scalable, profitable startups.  The National Science Foundation pays hundreds of startup teams each year to follow the process outlined in the book, and it's taught at Stanford, Berkeley, Columbia and more than 100 other leading universities worldwide.  Why?The Startup Owner's Manual guides you, step-by-step, as you put the Customer Development process to work. This method was created by renowned Silicon Valley startup expert Steve Blank, acknowledged catalyst of the \"Lean Startup\" movement, and tested and refined by him for more than a decade. This 608-page how-to guide includes over 100 charts, graphs, and diagrams, plus 77 valuable checklists that guide you as you drive your company toward profitability.  It will help you:·        Avoid the 9 deadly sins that destroy startups' chances for success·       Use the Customer Development method to bring your business idea to life·       Incorporate the Business Model Canvas as the organizing principle for startup hypotheses·       Identify your customers and determine how to \"get, keep and grow\" customers profitably·       Compute how you'll drive your startup to repeatable, scalable profits.",
    "publisher": "K & S Ranch",
    "publish_date": "",
    "notes": "Capa Dura (grifado)",
    "price": "R$ 100,00",
    "length": 608,
    "copies": 1
  },
  {
    "title": "Black Dog: Os Sonhos de Paul Nash",
    "image": "bh2285622c5c2aebd02431a173cb4fcd9c",
    "creators": "Dave McKean",
    "first_name": "Dave",
    "last_name": "McKean",
    "ean_isbn13": 9788594541192,
    "upc_isbn10": 8594541198,
    "description": "",
    "publisher": "Darkside",
    "publish_date": "1905-07-10",
    "notes": "Capa Dura",
    "price": "R$ 28,00",
    "length": "",
    "copies": 1
  }
]
